version: '3'

services:

  php:
    build: ./
    environment:
      PHP_IDE_CONFIG: "serverName=incentives"
    volumes:
      - ./:/app
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
